start_foto = 'AgACAgIAAxkBAAMFZpW0mlkUsfL04nK2BmJ-brZX3a0AApfYMRuOsLFIKd-7LTBNYeoBAAMCAAN5AAM1BA'

ubiycy_foto = 'AgACAgIAAxkBAAMHZpW0opv3pqxpS_z_Xx1SKnVXiiAAApjYMRuOsLFIikzQGDROoq4BAAMCAAN4AAM1BA'

cristal_foto = 'AgACAgIAAxkBAAMJZpW0qAvss68vOwcwYsbpByi3W84AApnYMRuOsLFIt6y_vYxK2xYBAAMCAAN4AAM1BA'

best_foto = 'AgACAgIAAxkBAAMLZpXAqUxmTLaM57S2EXSKA7roCpAAArnYMRuOsLFIpISRJiol2W8BAAMCAAN4AAM1BA'

vika = 'AgACAgIAAxkBAAIBRGaXMAMYDq_-OXAAAZr6tTxrGILaegACGN0xG4wfuUiffcdY07wx1AEAAwIAA3kAAzUE'

lexa = 'AgACAgIAAxkBAAIBRmaXMCbR3BPpwe7mHRueYc0l9haLAAIZ3TEbjB-5SLHTd46BMnTmAQADAgADeAADNQQ'

ub_1 = 'AgACAgIAAxkBAAMeZpXGX4pSvYz4cCj54nMgpEBAMjIAAsDYMRuOsLFIn8iaIO_kB8oBAAMCAAN5AAM1BA'
ub_2 = 'AgACAgIAAxkBAAN7ZpXbOo7cIvgk0b0wBub92TmLU8gAAiLZMRuOsLFIO4i90nH9eqQBAAMCAAN4AAM1BA'
ub_3 = 'AgACAgIAAxkBAAN9ZpXdpBUt1jOymVnIVvaRNzuom9gAAiTZMRuOsLFI1LcJxRfEn0ABAAMCAAN5AAM1BA'
ub_4 = 'AgACAgIAAxkBAAOPZpXggKQdfliLnLfJGpUJb_BofjIAAijZMRuOsLFIKyN9vFyCRX4BAAMCAAN5AAM1BA'
ub_5 = 'AgACAgIAAxkBAAORZpXhT1uf2Gs4OGeMoNytDm8bl9EAAinZMRuOsLFIY018iEM-1yABAAMCAAN5AAM1BA'
ub_6 = 'AgACAgIAAxkBAAOTZpXhfkGP7HzpmfQ62zFxE1LLDIsAAirZMRuOsLFIfqUE7z_jwcgBAAMCAAN5AAM1BA'
ub_7 = 'AgACAgIAAxkBAAOVZpXhjg4eAaqhkm3PjVT9SgMqR48AAivZMRuOsLFIZ8sjAAGs4qkYAQADAgADeQADNQQ'

sound_ub_dict = {'Харе Кришна': 'CQACAgIAAxkBAAMhZpXJKW9S356dUU3fg4vDymSMGJYAAtZKAAKOsLFIoMpkzD_4TMU1BA',
                 'Селебы': 'CQACAgIAAxkBAAMjZpXJR1vP2tVjMTn2jPLhE1ywZzwAAtdKAAKOsLFILLTsf_dKdPg1BA',
                 'Россия': 'CQACAgIAAxkBAAMlZpXJTjigemUHbYl_DrrS2Nq3WOIAAthKAAKOsLFIikKFhII6gd01BA',
                 'Что': 'CQACAgIAAxkBAAMnZpXJVyx5nMdbBXMo7-cOihR1XPkAAtlKAAKOsLFIVRg06OeXS5w1BA',
                 'Лударь': 'CQACAgIAAxkBAAMpZpXJWxelXrHO_lop1NS_L7B6jxAAAtpKAAKOsLFIbXOQA-muZ2g1BA',
                 'Андрей': 'CQACAgIAAxkBAAMrZpXJYuP_qAl98d0uAkexWLndpeUAAttKAAKOsLFIDKvUs8Ky71U1BA',
                 'Tiger': 'CQACAgIAAxkBAAMtZpXJaTduXidZzAVHJyYI18E0K0QAAtxKAAKOsLFIjdBlQKV9khI1BA',

                 'LGBT': 'CQACAgIAAxkBAANlZpXaGxmCFdhvpxY7c_MBg9jCreEAAupKAAKOsLFI4RPcgXE5dSQ1BA',
                 '30 лет': 'CQACAgIAAxkBAANnZpXaJdHu_EwkXjvyNz4ZimRvtIcAAutKAAKOsLFIdjVZpz_HZYY1BA',
                 'Селебы2': 'CQACAgIAAxkBAANpZpXaLfNbvKeunNN_ontPkWd8Sp8AAuxKAAKOsLFI0pCd96w-rrk1BA',
                 'Tiger2': 'CQACAgIAAxkBAANrZpXaNUBIAhXA9Fih3owFhBIPO1YAAu1KAAKOsLFIREIOBn68IMs1BA',
                 'Горжусь': 'CQACAgIAAxkBAANtZpXaPHrnbrt5QNllIPr56XDxY58AAu5KAAKOsLFIhoIi-iTyQVk1BA',
                 'Драка': 'CQACAgIAAxkBAANvZpXaRSkmMjjO7VN_k9CfaNk-tCsAAu9KAAKOsLFIxlRHrRK588o1BA',
                 'NLB': 'CQACAgIAAxkBAANxZpXaTR2dqPWdzp1v-h1YJxydBTYAAvBKAAKOsLFIGK5zc4pN01o1BA',

                 'Цивил': 'CQACAgIAAxkBAAN_ZpXd4D0hKSAJ7BRPHi6Dm1_HASoAAvJKAAKOsLFIuBgNMtakkPo1BA',
                 'Два': 'CQACAgIAAxkBAAOBZpXd6P9pBMOeW_TZwxdY705vBNwAAvNKAAKOsLFIThoGko0Oet41BA',
                 'Конец': 'CQACAgIAAxkBAAODZpXd71N7mXy_DyUXOeuAsXBPqjwAAvRKAAKOsLFIjrenM3mKsA01BA',

                 'Гипноз': 'CQACAgIAAxkBAAOFZpXgH89MCjED2n9ka68Qfg2PI-MAAvZKAAKOsLFIIwKJOHXAenw1BA',
                 'Счёт': 'CQACAgIAAxkBAAOHZpXgJJhPfT0uK4JlZrbFeXQrh8UAAvdKAAKOsLFIXNUS-zus4Gk1BA',
                 'Динамо': 'CQACAgIAAxkBAAOJZpXgKnbyjiTzp9hOjql2m4qeOUcAAvhKAAKOsLFIOgLNqHoOyyI1BA',
                 'Секретарша': 'CQACAgIAAxkBAAOLZpXgPNztPgABdaefzpsFEWhgIcyEAAL5SgACjrCxSKPPsqK0hCIcNQQ',
                 'Имя': 'CQACAgIAAxkBAAONZpXgP_VXYf6GoCJkjWarYGe_J8EAAvpKAAKOsLFIm6f3zrGI2OI1BA',

                 'На ступеньку': 'CQACAgIAAxkBAAOXZpXh0SmCLwWCxvASovIr24sqrh4AAvxKAAKOsLFIW1LR_iBqAAF_NQQ',
                 'Саларьево': 'CQACAgIAAxkBAAOZZpXh38gh7DWTLqHbsj78zMrfKmsAAv1KAAKOsLFIxj9LgrE6yGA1BA',
                 'Ножики': 'CQACAgIAAxkBAAObZpXh53B2EwPwe7PqgaLGme4TsxEAAv5KAAKOsLFIDCr6PH54adQ1BA',
                 'В пододеяльнике': 'CQACAgIAAxkBAAOdZpXh7HXKnnSY33e-FtXmR9DcBBMAAv9KAAKOsLFIWp9Oztuq4NA1BA',
                 'Шалость': 'CQACAgIAAxkBAAOfZpXh8QABn62XCMy8ieY54MOn6ItyAANLAAKOsLFIz8W3xovpJTk1BA',
                 'Не Виноваты': "CQACAgIAAxkBAAOhZpXh-OdS_Y45vXutLF6Yu0cKMYAAAgFLAAKOsLFIJoNMExmUTuE1BA",
                 'Даная': 'CQACAgIAAxkBAAOjZpXh_pwsov7klzNi1kT8amsjBfMAAgJLAAKOsLFIcHbEdlvYbRI1BA',

                 'В лесу': 'CQACAgIAAxkBAAOlZpXkpifo9VItpDcVCcSPEy_YRWwAAqhLAAKOsLFIYLrwBipBRus1BA',
                 'станция': 'CQACAgIAAxkBAAOnZpXkryzzq0_FpIaZen_qSGf37LMAAqlLAAKOsLFI2G_eLBnYpgQ1BA',
                 'Тошнота': 'CQACAgIAAxkBAAOpZpXksS3zZcKRQuoBlC3-Npkj4roAAqpLAAKOsLFIS14MyL8OAw01BA',
                 'Бей': 'CQACAgIAAxkBAAOrZpXktZevt78D2PDJnSTTj8fjzxoAAqtLAAKOsLFIIAtYj_Hc5V41BA',

                 'Антистресс': 'CQACAgIAAxkBAAOtZpXmVtJ86VGssOeWJr0JwWOxWgIAArFLAAKOsLFINvou0U3lkco1BA',
                 'реку': 'CQACAgIAAxkBAAOvZpXmWtvqSh0NaunOZjjSmZUCcugAArJLAAKOsLFIRb2Lhezlpbw1BA'

                 }

cr_1 = 'AgACAgIAAxkBAAPBZpb-c0L-f_2obCZnWYOzTMb1MM0AAuHcMRuMH7lIvIReQXWHnmwBAAMCAAN4AAM1BA'
cr_3 = 'AgACAgIAAxkBAAPFZpb-xfMMeTSoZlb3CklbJOXpFr0AAubcMRuMH7lI_c8D7t-q26IBAAMCAAN4AAM1BA'
cr_4 = 'AgACAgIAAxkBAAPHZpb-7G4ynyQ47bAq7NhAv7RNxO8AAufcMRuMH7lI6NKSwb1QgKoBAAMCAAN5AAM1BA'
cr_5 = 'AgACAgIAAxkBAAPJZpb_RoC1MhvAX-2EmLaFhjwdZVkAAurcMRuMH7lIKGe9_AqPVA8BAAMCAAN5AAM1BA'
cr_6 = 'AgACAgIAAxkBAAPLZpb_Yn4DuPr3cHq_c4V50lPllHYAAuzcMRuMH7lI-35P_RFhQjEBAAMCAAN5AAM1BA'
cr_7 = 'AgACAgIAAxkBAAPPZpcDMBBX0zIjoRGlx1hNURWcaDEAAvPcMRuMH7lICVTxEjFxMwIBAAMCAAN4AAM1BA'
cr_8 = 'AgACAgIAAxkBAAPNZpcAAYvCqWWc_rHjf2AzD5O2_yd4AALv3DEbjB-5SDnwFfqFuKGYAQADAgADeAADNQQ'

sound_cry_dict = {
    'Гривачи': 'CQACAgIAAxkBAAPRZpcSEoYGC9hfMv4xkzwQO7sf_esAAqBGAAKMH7lIqeioP2RiF8A1BA',
    'Sport': 'CQACAgIAAxkBAAPTZpcSH3JJCRbX1t3xVdd8Ompj-UYAAqFGAAKMH7lIsWTBZeQ33p81BA',
    'Не буду спорить': 'CQACAgIAAxkBAAPVZpcSKR-ZMaJ09Xld4pS2_pVze5cAAqJGAAKMH7lIuPRjXIJ43Fo1BA',
    'Футбол': 'CQACAgIAAxkBAAPXZpcSMTlTo_CJMPk78cIemBCQWjgAAqNGAAKMH7lIL9QUda1IEIQ1BA',

    'Кришна': 'CQACAgIAAxkBAAPZZpcT5gsj_JicEuxjnNriX9LU_KMAAqhGAAKMH7lIEesvG9aejng1BA',
    'Я': 'CQACAgIAAxkBAAPbZpcUIJ13yrNKEHx-TnpRWbM6iMUAAqlGAAKMH7lIPg9d1oFrfmo1BA',
    'Сауна': 'CQACAgIAAxkBAAPdZpcUJo-ZR4novciVJNMEtiHt5RYAAqpGAAKMH7lIT2oIQIAjquM1BA',
    'Плакал': 'CQACAgIAAxkBAAPfZpcWErKaWyvNSe1FVhbVid8pphcAArBGAAKMH7lIYnrXHoMwPEg1BA',
    'Русалка': 'CQACAgIAAxkBAAPhZpcWIR84P3ppqhIw8-5Ci8ScTQUAArFGAAKMH7lIQHTF0-__0Fs1BA',
    'Герой': 'CQACAgIAAxkBAAPjZpcWLUoPfrlfs4P2xA-f3I6rJGYAArJGAAKMH7lI_iHmoYkl23U1BA',
    'Сьюзи': 'CQACAgIAAxkBAAPlZpcWNe3ap6yVMmCHylwcQ2evMwYAArNGAAKMH7lImInv1201stM1BA',

    'Андрей': 'CQACAgIAAxkBAAPnZpcbgoiRrX0nrejw4S5vVS30YPYAAsVGAAKMH7lIvDcU6-CorAw1BA',
    'Ленина': 'CQACAgIAAxkBAAPpZpcbjQogBJUk5X5rQt29Y1fe8lwAAsZGAAKMH7lIEdRgmp2-AtE1BA',
    'Бескайфовая': 'CQACAgIAAxkBAAPrZpcbk7zxdnzZjvK8cSIqTuj3t7IAAsdGAAKMH7lItATcNX-ZwQo1BA',
    'Андеграундный рай': 'CQACAgIAAxkBAAPtZpcbmh81_4JPXP5iEXFUZs9e5CoAAshGAAKMH7lIF2PK_KYHUs81BA',
    'Сон': 'CQACAgIAAxkBAAPvZpcboOollrycWCSowG7RzJICJAkAAslGAAKMH7lIQZtXfeQ23Bs1BA',
    'Бурятия': 'CQACAgIAAxkBAAPxZpcbs-MRuoVZzgYV_GTKSPB9MrcAAstGAAKMH7lI8KCQyRCW3ng1BA',
    'Террористы': 'CQACAgIAAxkBAAPzZpcbvHB7KGY31VceodU7VYe3IIcAAsxGAAKMH7lI1F8RPHwAAQNsNQQ',
    'Вестник': 'CQACAgIAAxkBAAP1ZpcbwhVhjphEfPs3uN-ahuaZ9ewAAs5GAAKMH7lISiI9uvyDZV01BA',
    'Сама': 'CQACAgIAAxkBAAP3ZpcbyQ3l9LNF36k5LC0CAyfu4okAAs9GAAKMH7lIUHe9E5DXkbc1BA',

    'Sailor': 'CQACAgIAAxkBAAP5ZpcdzsyvGGeMquu8Pkd5z0LlXE4AAtFGAAKMH7lIKY45MiluAQ01BA',
    'Сериалы': 'CQACAgIAAxkBAAP7Zpcd1c8F7ITHzrrwJszUhmreH2kAAtJGAAKMH7lIUdqPLoA-8rc1BA',
    'Герой remix': 'CQACAgIAAxkBAAP9Zpcd3G1VspUk3o1W1EYyjBjcU8gAAtNGAAKMH7lI9YiWEYQr3so1BA',

    'Течение': 'CQACAgIAAxkBAAP_Zpcfic3TPioRuCIJOkuHCynz9GMAAtdGAAKMH7lIP1hsMc7CWXs1BA',
    'Пара': 'CQACAgIAAxkBAAIBAWaXH5CFM5vnVK4GzZT-xJ6pWLrkAALYRgACjB-5SPojVM4yHzLfNQQ',
    'Настя': 'CQACAgIAAxkBAAIBA2aXH5ZOgF1rCpJoqo1clDtxbSuiAALZRgACjB-5SNC1-vq9FyKYNQQ',
    'Грибы': 'CQACAgIAAxkBAAIBBWaXH5zFmnOIk9Tz4JNm9ZE8gGRzAALaRgACjB-5SJrVAuAPxFWUNQQ',
    'Корова': 'CQACAgIAAxkBAAIBB2aXH6IJ5peAJooLqpi0YM88AguRAALbRgACjB-5SOKgg4IBfm4vNQQ',

    'Без Названия': 'CQACAgIAAxkBAAIBCWaXI1UeFSZrgtyQE8296AG6JAJFAALhRgACjB-5SJyC9R-b91YQNQQ',
    'Гробы': 'CQACAgIAAxkBAAIBC2aXI1vlYFcf1KrtBxWzfI4HH_psAALiRgACjB-5SDcBfZUvY-5FNQQ',
    'одежда': 'CQACAgIAAxkBAAIBDWaXI2F-SeGA3zfmLZg8AAF8MuCUHAAC40YAAowfuUhx1zxM9QdEnDUE',
    'Насекомыми': 'CQACAgIAAxkBAAIBD2aXI2aXV5exehLnUp2dcCfViDd7AALkRgACjB-5SMLawitotd4HNQQ',
    'Танцы': 'CQACAgIAAxkBAAIBEWaXI3DsxTXzy6BS4JBaBGZNos28AALlRgACjB-5SPA38Y5DVRgnNQQ',
    'лучшие': 'CQACAgIAAxkBAAIBE2aXI3PBxChmRUlLZNIoPPtZ27TKAALmRgACjB-5SJqcV0GD3DocNQQ',
    'вижу': 'CQACAgIAAxkBAAIBFWaXI3mMFOy0VoE5ejMU18lKHkIXAALnRgACjB-5SB5nGkC2UlzTNQQ',
    'машине': 'CQACAgIAAxkBAAIBF2aXI31pgd9fvIYwiusSjIUjR_IqAALoRgACjB-5SKoO5Wn7kZLFNQQ',

    'Воскресенье': 'CQACAgIAAxkBAAIBG2aXJ0y5rQvmfXSNJY0-Qz8Ov1YeAALrRgACjB-5SAABYsZrft1eWjUE',
    'Dumb': 'CQACAgIAAxkBAAIBHWaXJ1W9Q30uBg6gvXyyuMYbcOk9AALsRgACjB-5SPATxfaREojFNQQ',
    'дикость': 'CQACAgIAAxkBAAIBH2aXJ1q1sjDq6i9rJEwqTW1mAb3mAALtRgACjB-5SMbyEICPeexJNQQ',
    'Скачать': 'CQACAgIAAxkBAAIBIWaXJ19TedPqrpnLZHiS8qQB54c2AALuRgACjB-5SMKDxAkyV33ZNQQ',
    'Жертва': 'CQACAgIAAxkBAAIBI2aXJ2eUm78o4NjTOjRwJ2wZCevAAALvRgACjB-5SJQOHcMJ_A7gNQQ'

}

izb_dict = {
    'Кришна': 'CQACAgIAAxkBAAPZZpcT5gsj_JicEuxjnNriX9LU_KMAAqhGAAKMH7lIEesvG9aejng1BA',
    'Русалка': 'CQACAgIAAxkBAAPhZpcWIR84P3ppqhIw8-5Ci8ScTQUAArFGAAKMH7lIQHTF0-__0Fs1BA',
    'Ленина': 'CQACAgIAAxkBAAPpZpcbjQogBJUk5X5rQt29Y1fe8lwAAsZGAAKMH7lIEdRgmp2-AtE1BA',
    'Андеграундный рай': 'CQACAgIAAxkBAAPtZpcbmh81_4JPXP5iEXFUZs9e5CoAAshGAAKMH7lIF2PK_KYHUs81BA',
    'Бурятия': 'CQACAgIAAxkBAAPxZpcbs-MRuoVZzgYV_GTKSPB9MrcAAstGAAKMH7lI8KCQyRCW3ng1BA',
    'вижу': 'CQACAgIAAxkBAAIBFWaXI3mMFOy0VoE5ejMU18lKHkIXAALnRgACjB-5SB5nGkC2UlzTNQQ',
    'лучшие': 'CQACAgIAAxkBAAIBE2aXI3PBxChmRUlLZNIoPPtZ27TKAALmRgACjB-5SJqcV0GD3DocNQQ',
    'Без Названия': 'CQACAgIAAxkBAAIBCWaXI1UeFSZrgtyQE8296AG6JAJFAALhRgACjB-5SJyC9R-b91YQNQQ',
    'Пинг-Понг': 'CQACAgIAAxkBAAIBGWaXJXmt1DW5rsYfOOPaNETCbf7cAALpRgACjB-5SBu1iYDrNgN4NQQ',
    'Воскресенье': 'CQACAgIAAxkBAAIBG2aXJ0y5rQvmfXSNJY0-Qz8Ov1YeAALrRgACjB-5SAABYsZrft1eWjUE',
    'В лесу': 'CQACAgIAAxkBAAOlZpXkpifo9VItpDcVCcSPEy_YRWwAAqhLAAKOsLFIYLrwBipBRus1BA',
    'Селебы': 'CQACAgIAAxkBAAMjZpXJR1vP2tVjMTn2jPLhE1ywZzwAAtdKAAKOsLFILLTsf_dKdPg1BA',
    'Горжусь': 'CQACAgIAAxkBAANtZpXaPHrnbrt5QNllIPr56XDxY58AAu5KAAKOsLFIhoIi-iTyQVk1BA',
    'Цивил': 'CQACAgIAAxkBAAN_ZpXd4D0hKSAJ7BRPHi6Dm1_HASoAAvJKAAKOsLFIuBgNMtakkPo1BA',
    'Шалость': 'CQACAgIAAxkBAAOfZpXh8QABn62XCMy8ieY54MOn6ItyAANLAAKOsLFIz8W3xovpJTk1BA',
    'LGBT2': 'CQACAgIAAxkBAAIBQGaXLN5XFQNbAAEnTc-2dFEC_qCGcAAC-0YAAowfuUhrxEGs-AzCkzUE',
    'реку': 'CQACAgIAAxkBAAOvZpXmWtvqSh0NaunOZjjSmZUCcugAArJLAAKOsLFIRb2Lhezlpbw1BA'

}
